version: '2'

# creates a shared network for all services on startup
networks:
  default:
    driver: bridge


services:

  cb_db:
    container_name: cb_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  cb_frontend:
      container_name: cb_frontend
      build: ./cb_frontend
      image: trahloff/cb_frontend
      restart: always
      depends_on:
       - cb_db
      ports:
      - "2020:8082"
