version: '2'

# creates a shared network for all services on startup
networks:
  default:
    driver: bridge


services:

  cb-db:
    container_name: cb-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  cb-frontend:
      container_name: cb-frontend
      build: ./cb-frontend
      image: trahloff/cb-frontend
      restart: always
      depends_on:
       - cb-db
      ports:
      - "2020:8082"
