version: '2'

networks:
  default:
    external:
      name: cb


services:

  cb-db:
    container_name: cb-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - "/mnt/cognitive-banking/postgres:/var/lib/postgresql/data"

  # cb-api:
  #   container_name: cb-api
  #   build: ./cb-api
  #   image: trahloff/cb-api
  #   depends_on:
  #     - kafka_broker
  #     - kafka_db
  #   ports:
  #     - "8081:8081"

  # cb-frontend:
  #     container_name: cb-frontend
  #     build: ./cb-frontend
  #     image: trahloff/cb-frontend
  #     depends_on:
  #      - cb-db
  #      - cb-api
  #     ports:
  #     - "8082:8082"
